### ISSUE TITLE
2D Image component ignoring rotation on Image as Plane

### ISSUE THREAD

**Issue by minim-sheba** [MozillaReality/hubs-blender-exporter#141]
**Description**
A 2D image component added to an image imported as plane in Blender, which is rotated (X 270 Y 0 Z 90), ignores the rotation and displays horizontally in Hubs instead of vertically as is Blender. I tried removing the component, undoing the rotation, then re-adding it after reconnecting the component in case it needed to be added in a particular order, but get the same behaviour each time. I also tried starting from a freshly imported image as plane, in case anything else was interfering, but ended up with the same result in Hubs in both Firefox and Chrome.

**To Reproduce**
- Create image as plane in Blender
- Add the Hubs 2D Image component and set up the image location
- Set position and rotation on the image either before or after adding the component
- Export, then import into Spoke and then view in Hubs - the position is captured, the rotation ignored

**Expected behavior**
2D image should display using the same rotation as the base object in Blender

**Screenshots**
![2022-09-30_13-51-30](https://user-images.githubusercontent.com/69302450/193273977-021f1b42-d08b-4609-aac9-dd980f20884c.jpg)

**Hardware** 
 - Add-on Release Version: 1.0.0 Beta 5
 - Blender Version: 3.3.0
 - OS: Windows 11

**Comment by Exairnous** [comment]
Hi, I think this is expected behavior actually.  Hubs uses the object rotation to determine the images component's rotation, so the resulting top of the image component will always be aligned with the object's Z axis.  With the rotations you specified, and the Show Axis option turned on in the Viewport Display panel for the object, I see that the object rotations make it perfectly horizontal (and facing up) with it's Z axis aligned to the global X axis, it's X axis aligned to the global Y axis, and it's Y axis aligned to the global Z axis.  When I followed your steps and imported it into Spoke and then viewed it in Hubs the rotations remained the same, i.e. it was horizontal and facing up, which is what I expected based on the transforms in Blender.  What you're seeing in Blender is the plane's mesh, which has no effect on the object's rotations and isn't even rendered when an image component is added.  Image components are designed to link in images that are hosted online, so you don't need to add them if you're importing the image as a plane and exporting it directly in the glTF file.  Unfortunately, there isn't really a good way to preview the orientation of the image component in Blender right now, but my suggestions would be to either enable the Show Axis option for the object and remember that Z points up, X points right, and negative Y indicates the front, or add in a plane and align it so that it's facing you in Front View (you'll probably just need to rotate it 90 degrees on the X axis) and then apply the rotation; you can also scale it to the correct aspect ratio and then apply the scale (be aware that using a mesh object will take up extra space in the glTF file).  Looks like the image component, and the video component, need a gizmo to properly display their orientation, but I hope this helps in the mean time.
