### ISSUE TITLE
Add missing scene-preview-camera components

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/hubs-blender-exporter#191]
**Is your feature request related to a problem? Please describe.**
The `scene-preview-camera` component is not available in the Blender add-on and are commonly used.

**Describe the solution you'd like**
Add support for both of them.

**Additional context**
this should be a good first issue for anyone interested. Both of them are just tag components so they could be easily added with just the definition similarly to what we do both other components like the `nav-mesh` one. You can find more info here about how to get started with components development here: https://github.com/MozillaReality/hubs-blender-exporter/wiki/Creating-custom-components

As a bonus, a gizmo could also be added for the `scene-preview-camera` component.

**Comment by sarhugo** [comment]
Hi, one doubt. Since hubs looks for a node named `scene-preview-camera` not sure how to proceed to handle this element as a component.

**Comment by Exairnous** [comment]
Yeah, I wasn't too sure about this one either, so I looked into it and it should be simple, but it ends up exposing a current limitation/bug of the add-on, so it's probably best to wait until that's fixed.

As far as I can tell, you need to add a component with the name "scene-preview-camera" and then you need to add a pre export hook to change the host's name to "scene-preview-camera", and then change it back to its original name with a post export hook (I'm not sure if this needs to be able to support multiple objects with this component or not.  I'd probably err on the side of caution though and support multiple objects in case the user accidentally has more than one, so you'll probably have to store the original names in a list or something).

However, it turns out that changing the object name can cause the object to be processed twice by the pre export hook, which will cause problems when trying to restore the original name (@keianhzo looks like we'll need to iterate over a copy of the blender bpy lists in `gltf_exporter.export_callback` instead of directly on them)

**Comment by keianhzo** [comment]
This should work just by adding a `scene-preview-camera` component, if it doesn't we need to look into it to see why not.
