### ISSUE TITLE
exporter

### ISSUE THREAD

**Issue by rdlmaulna** [MozillaReality/hubs-blender-exporter#67]

**Comment by matthewbcool** [comment]
Closing for lack of description, please try again and include the following - thank you!

**Description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
